### ISSUE TITLE
Cant get past login/registration screen

### ISSUE THREAD

**Issue by VincentBayliss** [cris1518/Flutter-Firestore-Fast-Calendar#2]
Hi, am interested in using this sample as the basis for a larger project but can't get this example up and running.  It sits at the Login/Register page with the spinning process indicator.  Have cloned this into Android Studio 4.0.1.  I have integrated into my Firestore project (i.e. dragged the json file into the app), updated any packages/etc... but still cant get past the login/register screen.

Any thoughts on what might be doing this?

**Comment by cris1518** [comment]
Good morning, what do you use to test the application? 
an android emulator or a physical device? . 
What version of android are you using to test the application?
**My Android Studio version is 4.0**
**Remember to activate the authentication service in firebase panel using the mail + password combination.**
